layout_spectrum: 0.1397849
typography_spectrum: 0.827957
color:
  saturation: 0.4798983
  lightness: 0.8096236
  brandStrength: 0.8694503
  rhythmicContrast: 0.3693372
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Testing at Work
