name: Testing at Work
favicon: null
layout_spectrum: 0.62919
typography_spectrum: 0.74899
title: Testing at work
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c1272d'
    - '#000000'
    - '#ffdecc'
    - '#268085'
    - '#bf9741'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
